config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main'), name='main'),
]

main/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('signup', views.SignupView.as_view(), name='signup'),
    path('login', auth_views.LoginView.as_view(
        template_name='main/registration/login.html', redirect_authenticated_user=True), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
]

main/models/base.py
from django.db import models
from django.utils import timezone

class SoftDeletionQuerySet(models.QuerySet):
    def delete(self):
        return super(SoftDeletionQuerySet, self).update(deleted_at=timezone.now())

    def hard_delete(self):
        return super(SoftDeletionQuerySet, self).delete()

    def alive(self):
        return self.filter(deleted_at=None)

    def dead(self):
        return self.exclude(deleted_at=None)

class SoftDeletionManager(models.Manager):
    def __init__(self, *args, **kwargs):
        self.alive_only = kwargs.pop('alive_only', True)
        super(SoftDeletionManager, self).__init__(*args, **kwargs)

    def get_queryset(self):
        if self.alive_only:
            return SoftDeletionQuerySet(self.model).filter(deleted_at=None)
        return SoftDeletionQuerySet(self.model)

    def hard_delete(self):
        return self.get_queryset().hard_delete()


class SoftDeletionModel(models.Model):
    deleted_at = models.DateTimeField(blank=True, null=True)

    objects = SoftDeletionManager()
    all_objects = SoftDeletionManager(alive_only=False)

    class Meta:
        abstract = True

    def delete(self):
        self.deleted_at = timezone.now()
        self.save()

    def hard_delete(self):
        super(SoftDeletionModel, self).delete()

main/models/user.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _


class UserManager(BaseUserManager):

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=255, blank=True)
    last_name = models.CharField(_('last name'), max_length=255, blank=True)
    user_name = models.CharField(_('user name'), max_length=255, blank=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        db_table = 'users'
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

main/forms/signup.py
from django.forms import Form
from django.forms.fields import EmailField, CharField
from django.forms.widgets import TextInput, PasswordInput, EmailInput

from main.models import User
from django.utils.translation import ugettext_lazy as _


class SignupForm(Form):
    first_name = CharField(
        max_length=255,
        required=True,
        widget=TextInput,
        label=_('First Name'))
    last_name = CharField(
        max_length=255,
        required=True,
        widget=TextInput,
        label=_('Last Name'))
    user_name = CharField(
        max_length=255,
        required=False,
        widget=TextInput,
        label=_('User Name'))
    email = EmailField(
        max_length=255,
        required=True,
        widget=EmailInput,
        label=_('E-mail Address'))
    password = CharField(
        min_length=8,
        max_length=255,
        required=True,
        widget=PasswordInput,
        label=_('Password'))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"

    def create_user(self):
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        user_name = self.cleaned_data.get('user_name')
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']
        user = None
        try:
            user = User.objects.create_user(
                email,
                password,
                first_name=first_name,
                last_name=last_name,
                user_name=user_name,)
        except:
            self.add_error(None, 'Error')
        return user

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).count() > 0:
            self.add_error('email', _('E-mail Address is already being used.'))
        return email

main/templates/main/base/footer.html
<footer class="py-4 text-center">
    &copy; {% now 'Y' %} example.
</footer>

main/templates/main/base/head.html
{% load common %}
{% if not title %}
    {% set title = 'Example Title' %}
{% endif %}
{% if not description %}
    {% set description = 'Example Description' %}
{% endif %}
{% if not keywords %}
    {% set keywords = 'keywords' %}
{% endif %}
{% if not og_image %}
    {% set og_image = '' %}
{% endif %}
{% if request.path == '/' %}
    {% set og_type = 'website' %}
{% else %}
    {% set og_type = 'article' %}
{% endif %}
{% if not site_name %}
    {% set site_name = 'Example Site' %}
{% endif %}

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
<title>{{ title }}</title>
<meta name="description" content="{{ description }}"/>
<meta name="keywords" content="service,{{ keywords }}"/>
<meta property="og:site_name" content="{{ site_name }}">
<meta property="og:title" content="{{ title }}"/>
<meta property="og:description" content="{{ description }}"/>
{% if og_image %}
    <meta property="og:image" content="{{ og_image }}"/>
{% endif %}
<meta property="og:type" content="{{ og_type }}"/>
<meta property="og:url" content="{{ request.build_absolute_uri }}"/>
<meta name="twitter:card" content="summary"/>
{% if twitter_site %}
    <meta name="twitter:site" content="{{ twitter_site }}"/>
{% endif %}
{% load static %}
<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/common.css' %}" type="text/css">
<link rel="dns-prefetch" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">
<link rel="canonical" href="{{ request.scheme }}://{{ request.get_host }}{{ request.path }}">

<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/popper.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>

main/templates/main/base/header.html
{% load i18n %}
<nav class="navbar navbar-expand-lg navbar-light mb-5">
    <div class="container">
    <a class="navbar-brand" href="{% url 'main:index' %}">Django</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:login' %}">{% trans 'Login' %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:signup' %}">{% trans 'Register' %}</a>
            </li>
        </ul>

    </div>
    </div>
</nav>

main/templates/main/base/layout.html
<!DOCTYPE html>
{% load i18n %}

<html lang="en">
<head>
    {% include 'main/base/head.html' %}
    {% include 'main/base/header.html' %}
    {% block css %}{% endblock %}
</head>
<body>
<div class="main">
    {% block content %}{% endblock %}
</div>
<hr/>
{% include 'main/base/footer.html' %}
{% block script %}{% endblock %}
</body>
</html>

main/templates/main/index.html
{% extends 'main/base/layout.html' %}

{% block content %}
    <div class="container">
        <h1>Hello world.</h1>
    </div>
{% endblock %}